import { supabase, isSupabaseConfigured, ResourceSubmission, SubmissionFormData } from '@/lib/supabase';

/**
 * Submit a new resource to the database
 */
export async function submitResource(data: SubmissionFormData): Promise<ResourceSubmission> {
  // Check if Supabase is configured
  if (!isSupabaseConfigured() || !supabase) {
    // If database is not configured, simulate a successful submission
    // This allows the form to work without database setup
    console.warn('Supabase not configured. Submission saved locally only.');
    return {
      ...data,
      submitter_name: data.submitterName,
      submitter_email: data.submitterEmail,
      status: 'pending',
      created_at: new Date().toISOString(),
    } as ResourceSubmission;
  }

  // Transform form data to database format
  const submission: Omit<ResourceSubmission, 'id' | 'created_at' | 'updated_at'> = {
    name: data.name,
    category: data.category,
    description: data.description,
    address: data.address || undefined,
    phone: data.phone || undefined,
    email: data.email || undefined,
    website: data.website || undefined,
    submitter_name: data.submitterName,
    submitter_email: data.submitterEmail,
    status: 'pending',
  };

  // Write-only insert: Do NOT use .select() since anon users cannot read the table
  // The insert succeeds, but trying to read it back would fail due to RLS
  const { error } = await supabase
    .from('resource_submissions')
    .insert([submission]);

  if (error) {
    console.error('Error submitting resource:', error);
    throw new Error(`Failed to submit resource: ${error.message}`);
  }

  // Return a constructed object since we can't read the inserted row back
  // The database will generate id, created_at, updated_at automatically
  return {
    ...submission,
    id: undefined, // Will be generated by database
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  } as ResourceSubmission;
}

/**
 * Get all pending submissions (for admin review)
 */
export async function getPendingSubmissions(): Promise<ResourceSubmission[]> {
  if (!isSupabaseConfigured() || !supabase) {
    console.warn('Supabase not configured. Cannot fetch submissions.');
    return [];
  }

  const { data, error } = await supabase
    .from('resource_submissions')
    .select('*')
    .eq('status', 'pending')
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching pending submissions:', error);
    throw new Error(`Failed to fetch submissions: ${error.message}`);
  }

  return data || [];
}

/**
 * Get all submissions (for admin dashboard)
 */
export async function getAllSubmissions(): Promise<ResourceSubmission[]> {
  if (!isSupabaseConfigured() || !supabase) {
    console.warn('Supabase not configured. Cannot fetch submissions.');
    return [];
  }

  const { data, error } = await supabase
    .from('resource_submissions')
    .select('*')
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching all submissions:', error);
    throw new Error(`Failed to fetch submissions: ${error.message}`);
  }

  return data || [];
}

/**
 * Update submission status (for admin approval/rejection)
 */
export async function updateSubmissionStatus(
  id: string,
  status: 'approved' | 'rejected',
  reviewNotes?: string
): Promise<ResourceSubmission> {
  if (!isSupabaseConfigured() || !supabase) {
    throw new Error('Supabase not configured. Cannot update submission.');
  }

  const { data, error } = await supabase
    .from('resource_submissions')
    .update({
      status,
      reviewed_at: new Date().toISOString(),
      review_notes: reviewNotes || null,
    })
    .eq('id', id)
    .select()
    .single();

  if (error) {
    console.error('Error updating submission:', error);
    throw new Error(`Failed to update submission: ${error.message}`);
  }

  return data;
}

/**
 * Get approved resources ready to be published
 */
export async function getApprovedResources(): Promise<ResourceSubmission[]> {
  if (!isSupabaseConfigured() || !supabase) {
    console.warn('Supabase not configured. Cannot fetch approved resources.');
    return [];
  }

  const { data, error } = await supabase
    .from('resource_submissions')
    .select('*')
    .eq('status', 'approved')
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching approved resources:', error);
    throw new Error(`Failed to fetch approved resources: ${error.message}`);
  }

  return data || [];
}

